image: gradle:jdk8-jammy
stages:
  - build
  - deploy
  - create
  - k8s
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
#  - sleep 30m
build:
  stage: build
  script: gradle build
  only:
    - tags
deploy:
  stage: deploy
  script:
    - 'gradle publish'
  only:
    - tags
  artifacts:
    paths:
      - /builds/muhammed.labeeb/java_build_gradle/app/build/libs
create-image:
  image: docker:19.03.6
  services:
    - docker:19.03.6-dind
  stage: create
  script:
  #  - sleep 30m
    - docker build -t $HARBOR_URL:v$CI_COMMIT_TAG .
    - echo $HARBOR_PASSWORD | docker login -u $HARBOR_USER --password-stdin $HARBOR_URL 
    - docker push $HARBOR_URL:v$CI_COMMIT_TAG
  dependencies:
    - deploy
  only:
    - tags
deploy_k8s:
  stage: k8s
  image: dtzar/helm-kubectl
  only:
    - tags
  script:
    - cd deployment
    - sed -i "s/<VERSION>/${CI_COMMIT_TAG}/g" deployment.yaml

