apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: gradle
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gitlab.mvtest-harbor.live:5050/muhammed.labeeb/java_build_gradle/gradle:v<VERSION>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gradle
